networks:
  db-net:
    name: db-net
    driver: bridge

services:
  mysql:
    container_name: "board-mysql"
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
    volumes:
      - ./infra/mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks: [db-net]
    ports:
      - "3306:3306"

